brand:
  name: Elena Katan
menu-string: Menu

nav:
  - title: Services
    url: '#services'
  - title: Portfolio
    url: '#portfolio'
  - title: About
    url: '#about'


copyright: Copyright &copy; Your Website 2018

social-buttons:
  - icon: fa fa-instagram
    url: 'http://instagram.com/nita_madewithlove' 
  - icon: fa fa-facebook
    url: 'facebook.com/nitamadewithlove'



modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
