brand:
  name: Nita, With Love
menu-string: Menu

nav:
  - title: Order
    url: '#portfolio'
  - title: About
    url: '#about'
  - title: Instagram
    url: 'http://instagram.com/nita_madewithlove'


copyright: Copyright &copy; Nita With Love 2018

social-buttons:
  - icon: fa fa-instagram
    url: 'http://instagram.com/nita_madewithlove' 
  - icon: fa fa-facebook
    url: 'http://facebook.com/nitamadewithlove'



modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
